#!/bin/sh

BASE_CMD="/usr/bin/systemback $@"

unlock() {
	[ -f /var/lib/pacman/db.lck ] && rm /var/lib/pacman/db.lck
	[ -f /run/systemback.lock ] && rm /run/systemback.lock
	[ -f /run/sbscheduler.lock ] && rm /run/sbscheduler.lock
}

if [ "$(id -u)" != 0 ]; then
	ENABLE_XHOST_ROOT=yes
	GRANTED_XHOST_ROOT=no
	if [ "$ENABLE_XHOST_ROOT" = yes ] && xhost 1>/dev/null 2>&1 && ! xhost | grep -qi 'SI:localuser:root$'; then
		xhost +SI:localuser:root
		GRANTED_XHOST_ROOT=yes
	fi

	pkexec --disable-internal-agent /usr/bin/env \
		DISPLAY="$DISPLAY" \
		XDG_SESSION_TYPE="$XDG_SESSION_TYPE" \
		DESKTOP_SESSION="$DESKTOP_SESSION" \
		"$0" $@
	status=$?

	[ "$GRANTED_XHOST_ROOT" = yes ] && xhost -SI:localuser:root

	exit $status
fi

trap 'unlock' EXIT

$BASE_CMD
